### ISSUE TITLE
Lógica validação

### ISSUE THREAD

**Issue by GuilhermeSant** [estacao-hack-2020/stay-safe#11]
Foi realizado a lógica para validação dos campos do formulario Ajuda e emitir aviso nos campos não preenchidos, porém precisaria de uma validação se todos os campos foram preenchidos para que possa clicar em enviar e emitir um Alert informando que formulario foi enviado.

**Comment by lucasliet** [comment]
não entendi, você fez a verificação se os campos estão vazios isso já não serve pra dizer se foram preenchidos? AHHAHA
só emitir um alert quando enviar

**Comment by GuilhermeSant** [comment]
![image](https://user-images.githubusercontent.com/60110573/101067387-41209700-3576-11eb-87e3-8f89fbf6d778.png)

Utilizei lógica que o Michel havia informado que possui um laço que valida todos os campos, se eu deixo o Alert no primeiro else ao preencher qualquer um dos campos do formulario ele ja emite o alert, porém deverá emitir somente se todos os campos estiverem preenchidos.

**Comment by lucasliet** [comment]
invés de fazer um else pra cada campo, você pode fazer um let validacao = true; por exemplo
e caso caia dentro de algum desses ifs de erro voce muda pra false
depois de todos os ifs vc cria mais um if que checa essse validacao ta true ou false, e só emite o alert se ele continua true

uma ideia sei la hahah teste ai

**Comment by GuilhermeSant** [comment]
vou testar valeu

**Comment by GuilhermeSant** [comment]
![image](https://user-images.githubusercontent.com/60110573/101074556-a62cba80-357f-11eb-94a6-bb6aebc627d6.png)

agora deu certo :D

sabe algum comando no JS que consiga fechar o modal após clicar em 'ok' no Alert ? kk

**Comment by lucasliet** [comment]
> sabe algum comando no JS que consiga fechar o modal após clicar em 'ok' no Alert ? kk


parece que da pra criar uma função de jquery que comunica com o modal, vi no [StackOverflow](https://stackoverflow.com/a/16493402)

```JS
$( ()  =>  $('#modalContact').modal('toggle') );

```

como a gente ta importando o jquery já pq o bootstrap pede, acho que só de chamar essa função assim já funciona
