### ISSUE TITLE
Form de cadastro de pedido de ajuda salvar em banco de dados

### ISSUE THREAD

**Issue by lucasliet** [estacao-hack-2020/stay-safe#13]
no momento estamos pedindo a cidade da pessoa, vamos fazer o front pegar a cidade e mandar pra api, ou a gente manda só latitude e longitude que pegar pra api mesmo?

e tem um outro porem, estamos pedindo e-mail, mas pessoal de idade que é usuário foco normalmente não gosta de mexer muito com e-mail, poderíamos até deixar como campo opcional, porém a gente teria que deixar pelo menos o campo de telefone obrigatório, mas ai tem que deixar aquele checkbox de "permito que tenham acesso ao meu telefone" ser obrigatório pra enviar também

**Comment by willcrdo** [comment]
Acho q podemos só pedir a autorização da pessoa pra compartilhar a localização, e pegar a latitude e longitude.

Referente ao e-mail, podemos manter como obrigatório mesmo, até para recuperação de senha, mas podemos mudar o label do checkbox para "utilizar o celular como forma de contato"

**Comment by lucasliet** [comment]
> Referente ao e-mail, podemos manter como obrigatório mesmo, até para recuperação de senha, mas podemos mudar o label do checkbox para "utilizar o celular como forma de contato"

Vai precisar de cadastro pra pedir ajuda?

**Comment by willcrdo** [comment]
> > Referente ao e-mail, podemos manter como obrigatório mesmo, até para recuperação de senha, mas podemos mudar o label do checkbox para "utilizar o celular como forma de contato"
> 
> Vai precisar de cadastro pra pedir ajuda?

Acho melhor não.

**Comment by lucasliet** [comment]
então melhor deixar o e-mail como opcional mesmo né ahaah, pra enviar ajuda pelo menos
