### ISSUE TITLE
Pegar Cidade de cada pedido de ajuda, a partir de sua latitude e longitude

### ISSUE THREAD

**Issue by lucasliet** [estacao-hack-2020/stay-safe#29]
https://github.com/estacao-hack-2020/stay-safe/blob/c51b2ef6abd2d99b15d96c189cc7cb83a7c8e3ea/js/exibeAjudas.js#L14

**Comment by eusouomichel** [comment]
pode pegar a cidade com a utilização de parte da api de geolocalização que eu estou utilizando, com ela da para pegar todos os dados com base no IP,

fetch(`http://ip-api.com/json`, {
    "method": "GET"
})
.then(function(response){
    response.json().then(function(data){
        mountHome(data.region);
    });
})
.catch(err => console.error(err));
