### ISSUE TITLE
@mmileski ajustar pro formato do brasil.io

### ISSUE THREAD

**Issue by lucasliet** [estacao-hack-2020/stay-safe#3]
## Consumindo API
fiz uma função basica no commit https://github.com/estacao-hack-2020/stay-safe/commit/2056eb48a5d10961b98d695cdd70b26323c75918 pra já pegar os dados do **brasil.io** de são paulo e colocar no html pra testar 
mas o formato que vem da api é esse
![apidata](https://user-images.githubusercontent.com/49222261/100833539-ed645f80-3448-11eb-8af1-5d81d3041969.png)
teriamos que alterar os dados que a gente exibe, acho que é mais viavel que procurar outra api com dados de cidade

## Autenticação
já fiz um cadastro no meu e-mail pra conseguir um token de acesso também, porque segundo o site [vai ser obrigatório o token pra acessar api](https://blog.brasil.io/2020/10/31/nossa-api-sera-obrigatoriamente-autenticada/)

## Documentação
a documentação deles ta desatualizada e incompleta, mas da pra seguir, eles não focam muito no uso da api e até desencorajam por conta de ser pesado pro server deles e tal
https://github.com/turicas/covid19-br/blob/master/api.md

**Comment by lucasliet** [comment]
@willcrdo já tinha conseguido pegar a localização atual?

eu fiz uma função que recebe o nome da cidade, 
se conseguir pegar a cidade pela localização @mmileski fechou

**Comment by willcrdo** [comment]
Pela API do google eu já estava conseguindo pegar a localização e mostrando ela no mapa

**Comment by lucasliet** [comment]
> Pela API do google eu já estava conseguindo pegar a localização e mostrando ela no mapa

ta [nessa branch](https://github.com/estacao-hack-2020/stay-safe/tree/feature/geolocalizacao) né, @mmileski você chegou a fazer merge dela na develop quando você mexeu nela?

**Comment by lucasliet** [comment]
Você ta alimentando a página de dados globais também?

**Comment by eusouomichel** [comment]
Alterei para outra API que estava mais completa, a BRASIL.io só tinha casos e mortes, a nova possui suspeitos e recuperados,  issue concluída e implementado na develop.
