### ISSUE TITLE
criar tela de dados globais

### ISSUE THREAD

**Issue by lucasliet** [estacao-hack-2020/stay-safe#8]
essa é a ultima tarefa que seria só html mesmo, vamo implementar ela numa tela nova pra entrega de amanhã, vai ficar de fora, vai ficar pra proxima sprint, o que a gente faz?

**Comment by mateuspeixoto** [comment]
acho que até amanhã as 18h tem chão, mas depende do pessoal

**Comment by lucasliet** [comment]
concluído na PR #10
